### PR TITLE
JPT-478: Improve stopJira to wait for Jira process only

### PR DESCRIPTION
**Pull request by KonradMarszalek**
JPT-478: Improve stopJira to wait for Jira process to shutdown instead of all Java processes on the node

### CODE REVIEW

**Comment by wyrzyk** [comment]
Is the issue key valid? 
Screenshot 2020-02-19 at 14 34 35

**Comment by wyrzyk** [comment]
Please consider updating CHANGELOG.

**Comment by KonradMarszalek** [comment]
> Is the issue key valid?
> Screenshot 2020-02-19 at 14 34 35

I dig this issue here: https://bulldog.internal.atlassian.com/browse/JPT-478. Probably I should use different issue tracker...

**Comment by dagguh** [comment]
I wanted to create a cross-fork PR with the integration-test, but it turns out @KonradMarszalek gave me write access to their fork 🙂 
Feel free to revoke it

**Comment by KonradMarszalek** [comment]
Closing this PR and opening new one with proper issue number

**Pull request closed without merging**
