### PR TITLE
JPERF-188: Improve stopJira to wait for Jira process to shutdown inst…

### PR DESCRIPTION
**Pull request by KonradMarszalek**
JPERF-188: Improve stopJira to wait for Jira process to shutdown instead of all Java processes on the node

Renamed branch and commit

Added Changelog entry

### CODE REVIEW

**Comment by dagguh** [comment]
FYI branch name doesn't really matter and the commit message can be amended and force-pushed. You have full permissions and control over your fork.

**Comment by dagguh** [comment]
Actually, [according to myself](https://ecosystem.atlassian.net/browse/JPERF-188?focusedCommentId=379710&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-379710), it's testable via the existing `AwsDatasetModificationIT`, which is better, because it directly pertains to dataset manipulations and covers both ends of the `CustomDatasetSource` - saving and reusing.
We just gotta add the second Java process and again, according to myself it's about using the `AtlassianSplunkForwarder`.
@KonradMarszalek LMK if you wanna adapt the test. If not, we're attacking this PR with @mzyromski-atlassian anyway, so we can cover that as an exercise.

**Comment by KonradMarszalek** [comment]
> @KonradMarszalek LMK if you wanna adapt the test

If possible I leave you to it as I just had coffee-break contribution capacity.

**Comment by KonradMarszalek** [comment]
> @KonradMarszalek LMK if you wanna adapt the test

If possible I leave you to it as I just had coffee-break contribution capacity.

**Comment by dagguh** [comment]
Awesome, thanks for the fix and the manual test ❤️

**Comment by dagguh** [comment]
Awesome, thanks for the fix and the manual test ❤️

**Comment by dagguh** [comment]
Adopted in https://github.com/atlassian/aws-infrastructure/pull/84 with CI

**Pull request closed without merging**
