### PR TITLE
JPERF-431 Fix duplicated virtual user node order

### PR DESCRIPTION
**Pull request by wyrzyk**

### CODE REVIEW

**Comment by wyrzyk** [comment]
@dagguh CircleCI doesn't start automatically if it's added after PR created.

**Comment by dagguh** [comment]
We *really* shouldn't avoid CI. Please.
We did this in the past and it hid real problems, which blocked contributions. Using admin powers is wrong. Work the problem instead of ignoring it.

AFAIK, closing and reopening the PR would retrigger CI.

**Comment by wyrzyk** [comment]
> We really shouldn't avoid CI. Please.
Who's avoiding the CI?

**Comment by wyrzyk** [comment]
> AFAIK, closing and reopening the PR would retrigger CI.

I have rewrote the commits to trigger the build.

**Comment by dagguh** [comment]
> @dagguh CircleCI doesn't start automatically if it's added after PR created.

I thought you removed the status checks. My bad.
So the big status checks info box at the bottom disappears after the merge. I mistook is as lack of status checks. Sorry for the confusion.

> I have rewrote the commits to trigger the build.

Oh, nice, so we have two ways of retriggering CI.

**Pull request merged**
